# -*- coding: utf-8 -*-

keycode_obj = {
    65: {'char': 'a', 'arr_val': 0},
    66: {'char': 'b', 'arr_val': 1},
    67: {'char': 'c', 'arr_val': 2},
    68: {'char': 'd', 'arr_val': 3},
    69: {'char': 'e', 'arr_val': 4},
    70: {'char': 'f', 'arr_val': 5},
    71: {'char': 'g', 'arr_val': 6},
    72: {'char': 'h', 'arr_val': 7},
    73: {'char': 'i', 'arr_val': 8},
    74: {'char': 'j', 'arr_val': 9},
    75: {'char': 'k', 'arr_val': 10},
    76: {'char': 'l', 'arr_val': 11},
    77: {'char': 'm', 'arr_val': 12},
    78: {'char': 'n', 'arr_val': 13},
    79: {'char': 'o', 'arr_val': 14},
    80: {'char': 'p', 'arr_val': 15},
    81: {'char': 'q', 'arr_val': 16},
    82: {'char': 'r', 'arr_val': 17},
    83: {'char': 's', 'arr_val': 18},
    84: {'char': 't', 'arr_val': 19},
    85: {'char': 'u', 'arr_val': 20},
    86: {'char': 'v', 'arr_val': 21},
    87: {'char': 'w', 'arr_val': 22},
    88: {'char': 'x', 'arr_val': 23},
    89: {'char': 'y', 'arr_val': 24},
    90: {'char': 'z', 'arr_val': 25},
    188:{'char': ',', 'arr_val': 26},
    190:{'char': '.', 'arr_val': 27},
    16: {'char': 'shift', 'arr_val': 28},
    32: {'char': 'space', 'arr_val': 29},
    8:  {'char': 'backspace', 'arr_val': 30}
}